version: "3.9"
services:
  app:
    image: node:16-alpine
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm i -g pnpm && pnpm install && node src/server.js"
    ports:
      - "3001:3001"
    depends_on:
      - redis

  redis:
    image: redis:latest